import { db } from "./db";
import { products, discountCodes } from "@shared/schema";

const SEED_PRODUCTS = [
  {
    nameEn: "Royal Maroon Embroidered Gown",
    nameAr: "فستان ماروني ملكي مطرز",
    descriptionEn: "A breathtaking evening gown in deep maroon with intricate gold thread embroidery along the bodice and sleeves. Handcrafted by skilled artisans, this piece blends traditional luxury with modern elegance.",
    descriptionAr: "فستان سهرة أخّاذ بلون الماروني العميق مع تطريز بخيوط ذهبية دقيقة على الصدر والأكمام. مصنوع يدوياً بواسطة حرفيين مهرة، تمزج هذه القطعة بين الفخامة التقليدية والأناقة العصرية.",
    price: 108900,
    originalPrice: 132000,
    category: "dresses",
    subcategory: "evening",
    images: ["/images/hero3.png"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Maroon & Gold", "Black & Gold", "Burgundy & Silver"],
    fabricEn: "Premium silk blend with hand embroidery",
    fabricAr: "مزيج حرير فاخر مع تطريز يدوي",
    inStock: true,
    featured: true,
    badge: "Bestseller",
    rating: 4.9,
    reviewCount: 187,
  },
  {
    nameEn: "Teal Pearl Jalabiya",
    nameAr: "جلابية لؤلؤة الفيروز",
    descriptionEn: "Exquisitely crafted jalabiya in rich teal blue with pearl and gold bead detailing. The loose, flowing silhouette offers both comfort and sophistication.",
    descriptionAr: "جلابية مصنوعة بدقة بلون الأزرق الفيروزي الغني مع تفاصيل من اللؤلؤ والخرز الذهبي. القصة الفضفاضة والانسيابية توفر الراحة والأناقة معاً.",
    price: 92000,
    originalPrice: null,
    category: "jalabiyas",
    subcategory: "embroidered",
    images: ["/images/hero3.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Teal & Gold", "Emerald & Silver", "Royal Blue & Gold"],
    fabricEn: "Soft chiffon with handmade beadwork",
    fabricAr: "شيفون ناعم مع أعمال خرز يدوية",
    inStock: true,
    featured: true,
    badge: "New",
    rating: 4.8,
    reviewCount: 94,
  },
  {
    nameEn: "Sage Green Embroidered Ensemble",
    nameAr: "طقم أخضر مريمية مطرز",
    descriptionEn: "A sophisticated sage green ensemble featuring intricate floral embroidery with gold accents. The relaxed silhouette with layered skirt creates an effortlessly elegant look perfect for celebrations.",
    descriptionAr: "طقم أنيق بلون الأخضر المريمية يتميز بتطريز زهري دقيق بلمسات ذهبية. القصة المريحة مع التنورة الطبقية تخلق إطلالة أنيقة مثالية للاحتفالات.",
    price: 118000,
    originalPrice: null,
    category: "dresses",
    subcategory: "couture",
    images: ["/images/hero1.png"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sage Green & Gold", "Mint & Silver", "Olive & Gold"],
    fabricEn: "Premium linen with gold thread embroidery",
    fabricAr: "كتان فاخر مع تطريز بخيوط ذهبية",
    inStock: true,
    featured: true,
    badge: "Exclusive",
    rating: 5.0,
    reviewCount: 62,
  },
  {
    nameEn: "Little Princess Party Dress",
    nameAr: "فستان حفلات الأميرة الصغيرة",
    descriptionEn: "An enchanting party dress for your little princess, crafted from the softest fabrics with delicate gold embroidery. Perfect for Eid celebrations, weddings, and birthday parties.",
    descriptionAr: "فستان حفلات ساحر لأميرتك الصغيرة، مصنوع من أنعم الأقمشة مع تطريز ذهبي رقيق. مثالي لاحتفالات العيد وحفلات الزفاف وأعياد الميلاد.",
    price: 47000,
    originalPrice: 58000,
    category: "kids",
    subcategory: "party",
    images: ["/images/hero1.png"],
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y"],
    colors: ["Pastel Pink & Gold", "Ivory & Gold", "Lavender & Silver"],
    fabricEn: "Soft tulle and cotton blend",
    fabricAr: "مزيج تول وقطن ناعم",
    inStock: true,
    featured: true,
    badge: "Popular",
    rating: 4.9,
    reviewCount: 231,
  },
  {
    nameEn: "Golden Pearl Luxury Gift Set",
    nameAr: "طقم هدايا Golden Pearl الفاخر",
    descriptionEn: "The ultimate luxury gift, beautifully presented in our signature golden packaging. This curated set includes a silk scarf with pearl-edge detailing, gold-tone accessories, and a personalized card.",
    descriptionAr: "الهدية الفاخرة المثالية، مقدمة بشكل جميل في تغليفنا الذهبي المميز. يتضمن هذا الطقم المنسق وشاح حرير بتفاصيل لؤلؤية وإكسسوارات ذهبية وبطاقة شخصية.",
    price: 73000,
    originalPrice: null,
    category: "gifts",
    subcategory: "premium",
    images: ["/images/logo.png"],
    sizes: ["One Size"],
    colors: ["Gold & Pearl", "Rose Gold & Pearl", "Silver & Pearl"],
    fabricEn: "Pure silk scarf included",
    fabricAr: "يتضمن وشاح حرير نقي",
    inStock: true,
    featured: true,
    badge: "Gift",
    rating: 5.0,
    reviewCount: 156,
  },
  {
    nameEn: "Blue Embroidered Tunic",
    nameAr: "تونيك أزرق مطرز",
    descriptionEn: "A stunning sky blue tunic with elaborate floral embroidery featuring birds, butterflies and blossom motifs. Paired with a flowing pale pink skirt for an ethereal look.",
    descriptionAr: "تونيك أزرق سماوي مذهل مع تطريز زهري متقن يضم زخارف الطيور والفراشات والأزهار. مقترن بتنورة وردية فاتحة لإطلالة أثيرية.",
    price: 103000,
    originalPrice: 116000,
    category: "dresses",
    subcategory: "tunic",
    images: ["/images/hero2.png"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sky Blue & Pink", "Powder Blue & Ivory", "Periwinkle & Gold"],
    fabricEn: "Crushed silk with detailed embroidery",
    fabricAr: "حرير مجعد مع تطريز مفصل",
    inStock: true,
    featured: false,
    badge: "Sale",
    rating: 4.7,
    reviewCount: 78,
  },
  {
    nameEn: "Classic Olive Embroidered Tunic",
    nameAr: "تونيك زيتوني كلاسيكي مطرز",
    descriptionEn: "Timeless elegance in olive green with garden-inspired embroidery featuring hot air balloons, birdcages, and floral motifs. A unique conversation piece for any occasion.",
    descriptionAr: "أناقة خالدة باللون الزيتوني مع تطريز مستوحى من الحدائق يضم مناطيد وأقفاص طيور وزخارف زهرية. قطعة فريدة لأي مناسبة.",
    price: 99500,
    originalPrice: null,
    category: "jalabiyas",
    subcategory: "classic",
    images: ["/images/hero2.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Olive & Multi", "Sage & Gold", "Forest Green & Silver"],
    fabricEn: "Premium organza with metallic thread",
    fabricAr: "أورجانزا فاخرة مع خيوط معدنية",
    inStock: true,
    featured: false,
    badge: null,
    rating: 4.8,
    reviewCount: 145,
  },
  {
    nameEn: "Eid Collection Kids Jalabiya",
    nameAr: "جلابية أطفال مجموعة العيد",
    descriptionEn: "Specially designed for Eid celebrations, this adorable kids' jalabiya features pastel tones with sparkling embroidery and a comfortable relaxed fit.",
    descriptionAr: "مصممة خصيصاً لاحتفالات العيد، هذه الجلابية الرائعة للأطفال تتميز بألوان باستيل مع تطريز لامع وقصة مريحة.",
    price: 33500,
    originalPrice: null,
    category: "kids",
    subcategory: "jalabiya",
    images: ["/images/hero1.png"],
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Mint & Gold", "Baby Blue & Silver", "Peach & Gold"],
    fabricEn: "Organic cotton with gentle embroidery",
    fabricAr: "قطن عضوي مع تطريز ناعم",
    inStock: true,
    featured: false,
    badge: "Eid",
    rating: 4.9,
    reviewCount: 198,
  },
  {
    nameEn: "Luxury Bridal Gift Box",
    nameAr: "صندوق هدايا عروس فاخر",
    descriptionEn: "Celebrate the bride-to-be with this exquisite gift box featuring premium items hand-selected for her special journey. Includes a silk robe, pearl hair accessories, and scented candle.",
    descriptionAr: "احتفلي بالعروس القادمة مع صندوق الهدايا الرائع هذا الذي يتضمن عناصر فاخرة مختارة يدوياً لرحلتها المميزة. يتضمن روب حرير وإكسسوارات شعر لؤلؤية وشمعة معطرة.",
    price: 131000,
    originalPrice: null,
    category: "gifts",
    subcategory: "bridal",
    images: ["/images/logo.png"],
    sizes: ["One Size"],
    colors: ["Bridal White & Gold", "Blush Pink & Gold", "Classic Gold"],
    fabricEn: "Silk robe included",
    fabricAr: "يتضمن روب حرير",
    inStock: true,
    featured: false,
    badge: "Luxury",
    rating: 5.0,
    reviewCount: 89,
  },
  {
    nameEn: "Pastel Blush Embroidered Set",
    nameAr: "طقم وردي باستيل مطرز",
    descriptionEn: "A delicate blush pink ensemble with subtle gold embroidered borders and pearl detailing. The layered silhouette with flowing dupatta creates a graceful, feminine look.",
    descriptionAr: "طقم وردي رقيق بحواف مطرزة بالذهب وتفاصيل لؤلؤية. القصة الطبقية مع الدوباتا الانسيابية تخلق إطلالة أنثوية رشيقة.",
    price: 112000,
    originalPrice: 128000,
    category: "dresses",
    subcategory: "formal",
    images: ["/images/hero1.png"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Blush Pink & Gold", "Champagne & Pearl", "Rose & Silver"],
    fabricEn: "Georgette with scalloped lace trim",
    fabricAr: "جورجيت مع حواف دانتيل مسننة",
    inStock: true,
    featured: true,
    badge: "New Arrival",
    rating: 4.8,
    reviewCount: 43,
  },
];

const SEED_DISCOUNTS = [
  {
    code: "WELCOME10",
    type: "percentage",
    value: 10,
    minOrder: 10000,
    maxUses: 1000,
    active: true,
  },
  {
    code: "EID25",
    type: "percentage",
    value: 25,
    minOrder: 20000,
    maxUses: 500,
    active: true,
  },
  {
    code: "FREESHIP",
    type: "fixed",
    value: 1500,
    minOrder: 15000,
    maxUses: null,
    active: true,
  },
];

export async function seedDatabase() {
  try {
    const existingProducts = await db.select().from(products);
    if (existingProducts.length === 0) {
      console.log("Seeding database with products...");
      await db.insert(products).values(SEED_PRODUCTS);
      console.log(`Seeded ${SEED_PRODUCTS.length} products`);

      await db.insert(discountCodes).values(SEED_DISCOUNTS);
      console.log(`Seeded ${SEED_DISCOUNTS.length} discount codes`);
    } else {
      console.log(`Database already has ${existingProducts.length} products, skipping seed`);
    }
  } catch (error) {
    console.error("Seed error:", error);
  }
}
